name: dawn # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '2021.02.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: Ghostery Dawn Privacy Browser # 79 char long summary
description: |
  The Ghostery Dawn Privacy Browser

confinement: strict
grade: stable

architectures:
  - build-on: amd64
    run-on: amd64

apps:
  dawn:
    command: Ghostery
    # command-chain: [tmpdir]
    # desktop: dawn.desktop
    extensions: [gnome-3-34]
    environment:
      HOME: "$SNAP_USER_COMMON"
      GTK_USE_PORTAL: 1
    slots:
      - dbus-daemon
      - mpris
    plugs:
      - avahi-observe
      - browser-sandbox
      - camera
      - cups-control
      - gsettings
      - home
      - joystick
      - network
      - network-observe
      - opengl
      - pulseaudio
      - removable-media
      - screen-inhibit-control
      - u2f-devices
      - unity7
      - upower-observe

plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: true

parts:
  dawn:
    plugin: dump
    #TODO programatic link
    source: ./Ghostery-2021.02.2.en-US.linux-x86_64.tar.bz2
    source-type: tar
    stage-packages:
      - libxt6
      - libdbus-glib-1-2
      - libasound2
      - libpulse0
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libmirclient9
      - desktop-file-utils
      - ffmpeg
      - libc-bin
      - locales-all
      - libcurl3-gnutls
    prime:
      - -usr/lib/*/libharfbuzz*
      - -usr/lib/*/*pango*

  # Find files provided by the base and platform snap and ensure they aren't
  # duplicated in this snap
  cleanup:
    after: [dawn]
    plugin: nil
    build-snaps: [core18, gnome-3-34-1804]
    override-prime: |
      set -eux
      for snap in "core18" "gnome-3-34-1804"; do
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: com.ghostery.dawn