name: ghostery-dawn # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '2021.02.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Ghostery Dawn Privacy Browser # 79 char long summary
description: |
  Community Driven Snap of the Ghostery Dawn Privacy Browser
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

grade: devel
confinement: classic

apps:
  ghostery-dawn-snap:
    command: ghostery
    aliases: [ghostery]

parts:
  ghostery-dawn:
    plugin: dump
    #TODO programatic link
    source: https://github.com/ghostery/user-agent-desktop/releases/download/2021-02-16-3/Ghostery-2021.02.1.en-US.linux-x86_64.tar.bz2
    source-type: tar